import {
  appendFile,
  lstat,
  readlink,
  readdir,
  rename,
  rm,
  symlink,
  unlink,
  writeFile,
} from "node:fs/promises";
import {
  basename,
  dirname,
  extname,
  isAbsolute,
  join,
  relative,
  resolve,
} from "node:path";
import {
  canonicalPath,
  createDirectoryExclusive,
  ensureDirectory,
  findExecutable,
  isPathInside,
  pathExists,
  readTextFile,
  removeDirectory,
  runCommand,
  standardExecutableFallbacks,
  writeTextFile,
} from "@daedalus/platform";
import type {
  AgentSession,
  GitStatus,
  PullRequestRef,
  SessionWorktree,
  Task,
  Workspace,
  WorkspaceContent,
  WorkspaceFile,
  WorkspaceFileEntry,
  WorkspaceRepository,
  RepositoryLibraryEntry,
} from "../domain";
import {
  saveWorkspaceInstructionFilesEnabled,
  type DaedalusConfig,
} from "../config";
import { DaedalusError, normalizeError } from "../errors";
import { removeSkillLink } from "./skills";
import type { SqliteRepositories } from "../repositories";
import type { WorkspaceService } from "./workspaces";

const LEGACY_BRIEF_TEMPLATE = `# Brief

## Objective

Describe what this workspace is trying to achieve.

## Scope

- In scope:
- Out of scope:

## Decisions

## Active work

## Blockers

## Next steps
`;

const BRIEF_TEMPLATE = `# Brief

## Objective

Describe what this workspace is trying to achieve.

## Scope

- In scope:
- Out of scope:

## Decisions
`;

const JOURNAL_TEMPLATE = `# Journal

Meaningful workspace decisions, progress, blockers, questions, handoffs, and
completed work are recorded here chronologically.
`;

const LEGACY_AGENTS_TEMPLATE = `<!-- Generated by Daedalus. Configure this in Settings. -->
# Daedalus workspace

Before working in this workspace:

1. Read \`BRIEF.md\`.
2. Read recent entries in \`JOURNAL.md\`.
3. Read \`.daedalus/workspace.json\` for workspace metadata.
4. Respect the access role of every attached repository.
5. Read project-specific instructions inside a repository before modifying it.
6. Add meaningful decisions, blockers, questions, and handoffs to \`JOURNAL.md\`.
`;

const WORKTREE_AGENTS_TEMPLATE = `<!-- Generated by Daedalus. Configure this in Settings. -->
# Daedalus workspace

Before working in this workspace:

1. Read \`BRIEF.md\`.
2. Read recent entries in \`JOURNAL.md\`.
3. Read \`.daedalus/workspace.json\` for workspace metadata.
4. Respect the access role of every attached repository.
5. Read project-specific instructions inside a repository before modifying it.
6. Treat \`repos/\` checkouts as read-only. Before modifying a repository, create only the worktree you need with \`daedal repo worktree create --session "$DAEDALUS_SESSION_ID" --repository <repository-name>\`, then work in the returned path.
7. Add meaningful decisions, blockers, questions, and handoffs to \`JOURNAL.md\`.
`;

export const AGENTS_TEMPLATE = `<!-- Generated by Daedalus. Configure this in Settings. -->
# Daedalus workspace

Workspace context:

1. \`BRIEF.md\` contains the durable objective, scope, and decisions. Consult it when that context is relevant.
2. \`JOURNAL.md\` contains chronological decisions, progress, blockers, questions, and handoffs. Read recent entries when prior workspace activity matters, and add meaningful updates when useful.
3. \`.daedalus/workspace.json\` contains workspace metadata.
4. Respect the access role of every attached repository.
5. Read project-specific instructions inside a repository before modifying it.
6. Treat \`repos/\` checkouts as read-only. Before modifying a repository, create only the worktree you need with \`daedal repo worktree create --session "$DAEDALUS_SESSION_ID" --repository <repository-name>\`, then work in the returned path.
`;

export const CLAUDE_TEMPLATE = `<!-- Generated by Daedalus. Configure this in Settings. -->
@AGENTS.md
`;

// A session starts in an empty directory under `<workspace>/worktrees/`, which
// is not a repository and not the workspace root. Providers that only read
// instruction files from the working directory therefore see nothing at all
// and open with no idea what the workspace is for. The session copy carries
// absolute paths because nothing here resolves relative to the workspace.
export function sessionInstructionsTemplate(workspacePath: string): string {
  return `<!-- Generated by Daedalus. Configure this in Settings. -->
# Daedalus workspace

This is an agent session directory inside the Daedalus workspace at
\`${workspacePath}\`. It starts empty on purpose; the workspace context lives in
the files below.

Workspace context:

1. \`${join(workspacePath, "BRIEF.md")}\` contains the durable objective, scope, and decisions. Consult it when that context is relevant.
2. \`${join(workspacePath, "JOURNAL.md")}\` contains chronological decisions, progress, blockers, questions, and handoffs. Read recent entries when prior workspace activity matters, and add meaningful updates when useful.
3. \`${join(workspacePath, ".daedalus", "workspace.json")}\` contains workspace metadata.
4. Respect the access role of every attached repository.
5. Read project-specific instructions inside a repository before modifying it.
6. Treat the checkouts under \`${join(workspacePath, "repos")}\` as read-only. Before modifying a repository, create only the worktree you need with \`daedal repo worktree create --session "$DAEDALUS_SESSION_ID" --repository <repository-name>\`, then work in the returned path.
`;
}

const SAFE_SEGMENT = /[^a-z0-9]+/g;
const MAX_VIEWABLE_FILE_BYTES = 1024 * 1024;

/**
 * Top-level folders Daedalus creates and keeps pointing at.
 * `ensureWorkspaceContentFiles` recreates them, so losing one is survivable,
 * but `repos/` and `worktrees/` hold checkouts and session working trees that
 * database rows name by path — renaming either orphans those rows silently.
 */
/**
 * A greyed-out menu item with no explanation reads as a broken one — that is
 * exactly how the first version of this was reported, as "delete does
 * nothing". The reason travels with the entry so the menu can say it.
 */
function immutableEntryFields(
  refusal: { code: "VALIDATION" | "CONFLICT"; message: string } | undefined,
): { mutable: boolean; immutableReason?: string } {
  return refusal
    ? { mutable: false, immutableReason: refusal.message }
    : { mutable: true };
}

const MANAGED_WORKSPACE_DIRECTORIES = ["repos", "worktrees", "artifacts"];

/**
 * Entries at the workspace root that `ensureWorkspaceContentFiles` recreates.
 *
 * Removing one appeared to do nothing, and that was worse than a refusal: the
 * delete succeeded, and the very next `workspaceContentGet` — which the
 * desktop fires after every mutation — put the file straight back, so from the
 * tree the menu item looked broken. Renaming was worse still, because the
 * rename also succeeded and the original then regenerated beside it, silently
 * leaving two files.
 *
 * Only at the root: a `BRIEF.md` inside a folder is an ordinary file.
 */
const REGENERATED_WORKSPACE_ENTRIES = [
  "BRIEF.md",
  "JOURNAL.md",
  "AGENTS.md",
  "CLAUDE.md",
  ".agents",
  ".claude",
];

/**
 * Top-level folders Daedalus creates and keeps pointing at.
 * `ensureWorkspaceContentFiles` recreates them, so losing one is survivable,
 * but `repos/` and `worktrees/` hold checkouts and session working trees that
 * database rows name by path — renaming either orphans those rows silently.
 */

/** One valid path segment, shared by every verb that takes a new name. */
function assertEntryName(value: string): string {
  const name = value.trim();
  if (
    !name ||
    name === "." ||
    name === ".." ||
    name.length > 255 ||
    /[\\/\0]/.test(name)
  )
    throw new DaedalusError(
      "VALIDATION",
      "File and folder names must be one valid path segment",
    );
  return name;
}
const GH_EXECUTABLE_FALLBACKS = standardExecutableFallbacks("gh");

type GitHubRepositoryResponse = {
  name?: string;
  full_name?: string;
  clone_url?: string;
};

export function parseGitHubRepositoryPages(value: string): Array<{
  name: string;
  nameWithOwner: string;
  remoteUrl: string;
}> {
  const pages = JSON.parse(value) as GitHubRepositoryResponse[][];
  const seen = new Set<string>();
  return pages.flatMap((page) =>
    page.flatMap((repository) => {
      if (!repository.name || !repository.full_name || !repository.clone_url)
        return [];
      const identity = repository.full_name.toLowerCase();
      if (seen.has(identity)) return [];
      seen.add(identity);
      return [
        {
          name: repository.name,
          nameWithOwner: repository.full_name,
          remoteUrl: repository.clone_url,
        },
      ];
    }),
  );
}

export function pathSegment(value: string, fallback: string): string {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(SAFE_SEGMENT, "-")
      .replace(/^-+|-+$/g, "") || fallback
  ).slice(0, 80);
}

export function sessionWorktreeRelativePath(input: {
  task: Pick<Task, "id" | "title">;
  sessionId: string;
  repositoryName: string;
}): string {
  const taskDirectory = `${input.task.id}-${pathSegment(input.task.title, "task")}`;
  return join(
    "worktrees",
    taskDirectory,
    input.sessionId,
    pathSegment(input.repositoryName, "repository"),
  );
}

async function createIfMissing(path: string, contents: string): Promise<void> {
  if (await pathExists(path)) return;
  try {
    await writeTextFile(path, contents);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
  }
}

async function syncBriefFile(path: string): Promise<void> {
  if (!(await pathExists(path))) {
    await createIfMissing(path, BRIEF_TEMPLATE);
    return;
  }
  if (await generatedFileMatches(path, LEGACY_BRIEF_TEMPLATE))
    await writeFile(path, BRIEF_TEMPLATE, "utf8");
}

async function generatedFileMatches(
  path: string,
  generated: string,
): Promise<boolean> {
  if (!(await pathExists(path))) return false;
  const stats = await lstat(path);
  return stats.isFile() && !stats.isSymbolicLink()
    ? (await readTextFile(path)) === generated
    : false;
}

async function generatedFileMatchesAny(
  path: string,
  generated: string[],
): Promise<boolean> {
  for (const contents of generated)
    if (await generatedFileMatches(path, contents)) return true;
  return false;
}

async function removeIfGenerated(
  path: string,
  generated: string[],
): Promise<void> {
  if (await generatedFileMatchesAny(path, generated)) await unlink(path);
}

/**
 * Retires the per-workspace skill links this function used to create.
 *
 * Skills are installed globally now, into the providers' own personal
 * directories, so a link inside every workspace is a second copy of a decision
 * that is already made once. Only a symlink still pointing at the managed
 * package is removed, so a real directory a user put here survives.
 */
async function removeLegacyWorkspaceSkillLinks(
  path: string,
  daedalusHome: string,
): Promise<void> {
  const target = join(daedalusHome, "skills", "daedalus-control");
  await Promise.all([
    removeSkillLink(
      join(path, ".agents", "skills", "daedalus-control"),
      target,
    ),
    removeSkillLink(
      join(path, ".claude", "skills", "daedalus-control"),
      target,
    ),
  ]);
}

export async function syncWorkspaceInstructionFiles(
  path: string,
  enabled: boolean,
  daedalusHome: string,
): Promise<void> {
  const agentsPath = join(path, "AGENTS.md");
  const claudePath = join(path, "CLAUDE.md");
  await removeLegacyWorkspaceSkillLinks(path, daedalusHome);
  if (!enabled) {
    await Promise.all([
      removeIfGenerated(agentsPath, [
        AGENTS_TEMPLATE,
        WORKTREE_AGENTS_TEMPLATE,
        LEGACY_AGENTS_TEMPLATE,
      ]),
      removeIfGenerated(claudePath, [CLAUDE_TEMPLATE]),
    ]);
    return;
  }
  const agentsExists = await pathExists(agentsPath);
  if (!agentsExists) await createIfMissing(agentsPath, AGENTS_TEMPLATE);
  const agentsIsGenerated =
    !agentsExists ||
    (await generatedFileMatchesAny(agentsPath, [
      AGENTS_TEMPLATE,
      WORKTREE_AGENTS_TEMPLATE,
      LEGACY_AGENTS_TEMPLATE,
    ]));
  if (
    agentsExists &&
    agentsIsGenerated &&
    !(await generatedFileMatches(agentsPath, AGENTS_TEMPLATE))
  )
    await writeFile(agentsPath, AGENTS_TEMPLATE, "utf8");
  if (agentsIsGenerated) await createIfMissing(claudePath, CLAUDE_TEMPLATE);
}

export async function ensureSessionInstructionFiles(
  sessionPath: string,
  workspacePath: string,
  daedalusHome: string,
  enabled: boolean,
): Promise<void> {
  const agentsPath = join(sessionPath, "AGENTS.md");
  const template = sessionInstructionsTemplate(workspacePath);
  await removeLegacyWorkspaceSkillLinks(sessionPath, daedalusHome);
  if (!enabled) {
    await removeIfGenerated(agentsPath, [template]);
    return;
  }
  await createIfMissing(agentsPath, template);
}

export async function ensureWorkspaceContentFiles(
  path: string,
  daedalusHome: string,
  instructionFilesEnabled = true,
): Promise<void> {
  await Promise.all([
    ensureDirectory(join(path, "artifacts")),
    ensureDirectory(join(path, "repos")),
    ensureDirectory(join(path, "worktrees")),
    syncBriefFile(join(path, "BRIEF.md")),
    createIfMissing(join(path, "JOURNAL.md"), JOURNAL_TEMPLATE),
  ]);
  await syncWorkspaceInstructionFiles(
    path,
    instructionFilesEnabled,
    daedalusHome,
  );
}

function repositoryName(value: string): string {
  const name = pathSegment(value, "");
  if (!name)
    throw new DaedalusError(
      "VALIDATION",
      "Repository name must contain a letter or number",
    );
  return name;
}

function remoteRepositoryName(remoteUrl: string): string {
  const withoutQuery = remoteUrl.replace(/[?#].*$/, "").replace(/[\\/]$/, "");
  return repositoryName(basename(withoutQuery).replace(/\.git$/i, ""));
}

const REMOTE_TRACKING_REFSPEC = "+refs/heads/*:refs/remotes/origin/*";

const GIT_NETWORK_ENVIRONMENT = {
  GIT_TERMINAL_PROMPT: "0",
  GIT_SSH_COMMAND: "ssh -oBatchMode=yes",
};

// A bare clone already carries every branch under `refs/heads/*`, but nothing
// under `refs/remotes/origin/*` — which is what worktree creation and status
// comparison resolve against. Populating them by fetching `origin` again costs
// a network round trip that transfers no objects, and `remote set-head --auto`
// costs a second one to learn a default branch the clone already recorded in
// `HEAD`. Both are avoidable: the refs are copied from the repository to
// itself, and the default branch is read locally. Measured against a small
// GitHub repository the two round trips cost about a second, which is more
// than the clone itself and is paid per repository.
async function seedRemoteTrackingRefs(
  git: string,
  gitDirectory: string,
): Promise<string> {
  const run = (args: string[]) =>
    runCommand(git, ["--git-dir", gitDirectory, ...args]);
  const configure = await run([
    "config",
    "remote.origin.fetch",
    REMOTE_TRACKING_REFSPEC,
  ]);
  if (configure.exitCode !== 0)
    throw new DaedalusError(
      "DEPENDENCY",
      `Could not configure repository remote: ${configure.stderr.trim()}`,
    );
  const head = await run(["symbolic-ref", "--short", "HEAD"]);
  const defaultBranch = head.stdout.trim();
  if (head.exitCode !== 0 || !defaultBranch)
    throw new DaedalusError(
      "DEPENDENCY",
      "The repository remote does not advertise a default branch",
    );
  // Fetching `origin` rather than copying the repository's own refs into place.
  // The copy needed no network and was faster, but on a case-insensitive
  // filesystem it refuses outright for any repository whose remote carries two
  // branches differing only in case — git cannot write both as loose refs, and
  // fetching from a local path is the shape that takes that route. Fetching the
  // remote handles the same repository without complaint, so the round trip is
  // the price of working on the repositories people actually have.
  const copy = await runCommand(
    git,
    ["--git-dir", gitDirectory, "fetch", "--prune", "origin"],
    { env: GIT_NETWORK_ENVIRONMENT },
  );
  if (copy.exitCode !== 0)
    throw new DaedalusError(
      "DEPENDENCY",
      `Could not record the remote branches: ${copy.stderr.trim() || copy.stdout.trim()}`,
    );
  const symbolic = await run([
    "symbolic-ref",
    "refs/remotes/origin/HEAD",
    `refs/remotes/origin/${defaultBranch}`,
  ]);
  if (symbolic.exitCode !== 0)
    throw new DaedalusError(
      "DEPENDENCY",
      `Could not record the remote default branch: ${symbolic.stderr.trim() || symbolic.stdout.trim()}`,
    );
  return defaultBranch;
}

// What a working tree is holding that exists nowhere else — the only thing
// that makes removing it destructive.
//
// This is deliberately not `gitStatus.ahead`. A row shows "ahead 2" to say how
// far the agent has moved from the branch it started on, which stays true
// after the branch is pushed; safety asks whether those commits are reachable
// from anything on the remote, and pushing is exactly what makes them so.
// Measuring removability with `ahead` produced a guard that told the user to
// push and then refused just the same afterwards.
async function worktreeHeldWork(
  repository: WorkspaceRepository,
  worktree: SessionWorktree,
): Promise<{ uncommittedFiles: number; unreachableCommits: number }> {
  const git = findExecutable("git");
  // Nothing readable is nothing to lose: a tree whose directory is gone, or a
  // machine with no git, must not become permanently unremovable.
  if (!git || !(await pathExists(worktree.path)))
    return { uncommittedFiles: 0, unreachableCommits: 0 };
  // Also read-only, and also asked while an agent may be working in the tree.
  const run = (args: string[]) =>
    runCommand(git, ["--no-optional-locks", "-C", worktree.path, ...args]);
  const status = await run([
    "status",
    "--porcelain=v1",
    "-z",
    "--untracked-files=normal",
  ]);
  if (status.exitCode !== 0)
    return { uncommittedFiles: 0, unreachableCommits: 0 };
  const elsewhere: string[] = [];
  for (const reference of [
    repository.baseBranch ? `refs/remotes/origin/${repository.baseBranch}` : "",
    repository.baseBranch ? `refs/heads/${repository.baseBranch}` : "",
    `refs/remotes/origin/${worktree.branchName}`,
  ]) {
    if (!reference) continue;
    const resolved = await run(["rev-parse", "--verify", "--quiet", reference]);
    if (resolved.exitCode === 0) elsewhere.push(reference);
  }
  const uncommittedFiles = status.stdout.split("\0").filter(Boolean).length;
  // With nothing to compare against there is nothing to call unique. Counting
  // `HEAD` alone would report the repository's whole history, which would make
  // an untouched working tree permanently unremovable.
  if (elsewhere.length === 0)
    return { uncommittedFiles, unreachableCommits: 0 };
  const unique = await run([
    "rev-list",
    "--count",
    "HEAD",
    "--not",
    ...elsewhere,
  ]);
  return {
    uncommittedFiles,
    unreachableCommits:
      unique.exitCode === 0
        ? Number.parseInt(unique.stdout.trim(), 10) || 0
        : 0,
  };
}

// Long enough that a burst of changes does not start a pass each, short enough
// that a badge is never meaningfully behind what the user just did — and the
// actions that change something ask for a pass directly rather than waiting.
const STATUS_REFRESH_INTERVAL_MS = 1_000;

const statusKey = (path: string) => resolve(path);

const UNAVAILABLE_STATUS: GitStatus = {
  state: "unavailable",
  changedFiles: 0,
  ahead: 0,
  behind: 0,
};

// Shared by the read-only checkout under `repos/` and by session worktrees.
// Both answer the same two questions — what is uncommitted here, and how far
// has this tree moved from the branch it started on — so both are compared
// against `refs/remotes/origin/<baseBranch>` rather than against whatever
// upstream the tree happens to have.
async function gitStatusAt(
  path: string | null,
  baseBranch: string | null,
): Promise<GitStatus> {
  if (!path || !baseBranch) return UNAVAILABLE_STATUS;
  const git = findExecutable("git");
  if (!git || !(await pathExists(path))) return UNAVAILABLE_STATUS;
  const [status, comparison] = await Promise.all([
    runCommand(git, [
      // Reading a working tree must never be able to break what is working in
      // it. `git status` refreshes the index, which takes `index.lock`, and an
      // agent running `git add` in the same worktree at that moment fails with
      // exit 128. This is polled in the background across every tree, so
      // without this flag Daedalus is a race against its own agents.
      "--no-optional-locks",
      "-C",
      path,
      "status",
      "--porcelain=v1",
      "-z",
      "--untracked-files=normal",
    ]),
    runCommand(git, [
      "-C",
      path,
      "rev-list",
      "--left-right",
      "--count",
      `HEAD...refs/remotes/origin/${baseBranch}`,
    ]),
  ]);
  if (status.exitCode !== 0 || comparison.exitCode !== 0)
    return UNAVAILABLE_STATUS;
  const [ahead = 0, behind = 0] = comparison.stdout
    .trim()
    .split(/\s+/)
    .map((value) => Number.parseInt(value, 10) || 0);
  const changedFiles = status.stdout.split("\0").filter(Boolean).length;
  // The size of the diff a reviewer would read. Three-dot, so work that
  // landed on the base branch since this tree branched is not counted as its.
  let filesAhead: number | undefined;
  if (ahead > 0) {
    const diff = await runCommand(git, [
      "--no-optional-locks",
      "-C",
      path,
      "diff",
      "--name-only",
      "-z",
      `refs/remotes/origin/${baseBranch}...HEAD`,
    ]);
    if (diff.exitCode === 0)
      filesAhead = diff.stdout.split("\0").filter(Boolean).length;
  }
  const state = changedFiles
    ? ("modified" as const)
    : ahead && behind
      ? ("diverged" as const)
      : behind
        ? ("behind" as const)
        : ahead
          ? ("ahead" as const)
          : ("clean" as const);
  return {
    state,
    changedFiles,
    ahead,
    behind,
    ...(filesAhead === undefined ? {} : { filesAhead }),
  };
}

/**
 * Editors that install a command-line launcher, in the order to try them. A
 * packaged app inherits no shell PATH, so each also names where its app
 * bundle keeps the launcher when the user never put it on PATH.
 */
const EDITOR_LAUNCHERS: Array<{
  name: string;
  command: string;
  fallbacks: string[];
}> = [
  {
    name: "VS Code",
    command: "code",
    fallbacks: [
      ...standardExecutableFallbacks("code"),
      "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code",
    ],
  },
  {
    name: "Cursor",
    command: "cursor",
    fallbacks: [
      ...standardExecutableFallbacks("cursor"),
      "/Applications/Cursor.app/Contents/Resources/app/bin/cursor",
    ],
  },
  {
    name: "Zed",
    command: "zed",
    fallbacks: [
      ...standardExecutableFallbacks("zed"),
      "/Applications/Zed.app/Contents/MacOS/cli",
    ],
  },
];

/** How often one branch is asked about. `gh` is a network round trip. */
const PULL_REQUEST_REFRESH_MS = 60_000;

/**
 * Reads `gh pr view --json number,url,state,isDraft`. Anything else, including
 * a partial answer, is no pull request: a link that might be wrong is worse
 * than no link.
 */
export function parsePullRequestView(
  stdout: string,
): PullRequestRef | undefined {
  try {
    const value = JSON.parse(stdout) as Partial<Record<string, unknown>>;
    const state = value.state;
    if (
      typeof value.number !== "number" ||
      !Number.isInteger(value.number) ||
      typeof value.url !== "string" ||
      !/^https:\/\//.test(value.url) ||
      (state !== "OPEN" && state !== "CLOSED" && state !== "MERGED")
    )
      return undefined;
    return {
      number: value.number,
      url: value.url,
      state,
      isDraft: value.isDraft === true,
    };
  } catch {
    return undefined;
  }
}

const samePullRequest = (
  left: PullRequestRef | undefined,
  right: PullRequestRef | undefined,
) =>
  left === right ||
  (left !== undefined &&
    right !== undefined &&
    left.number === right.number &&
    left.url === right.url &&
    left.state === right.state &&
    left.isDraft === right.isDraft);

export class WorkspaceContentService {
  /** In-flight preparations, so a shutdown or a test can wait for them. */
  private readonly preparations = new Map<string, Promise<void>>();
  /** Last measured status per working tree, keyed by path. */
  private readonly gitStatusCache = new Map<string, GitStatus>();
  /**
   * Last `gh` answer per worktree path. `checkedAt` is kept even when nothing
   * was found, so a branch with no pull request is not asked about every
   * second.
   */
  private readonly pullRequestCache = new Map<
    string,
    { checkedAt: number; value?: PullRequestRef }
  >();
  private statusRefresh?: Promise<void>;
  /**
   * What the next pass has to cover. `null` is every workspace, which is what
   * the board asks for; a string is one. Two different single workspaces
   * asking during one pass widen it to every workspace rather than dropping
   * one of them.
   */
  private statusRefreshAgain: string | null | undefined;
  private lastStatusRefreshAt = 0;

  constructor(
    private readonly repositories: SqliteRepositories,
    private readonly workspaces: WorkspaceService,
    private readonly config: DaedalusConfig,
    /**
     * Called when a repository finishes preparing. The work happens outside
     * any request, so without this the desktop would show "preparing" until
     * something else happened to refresh it.
     */
    private readonly onRepositoriesChanged: () => void = () => {},
  ) {}

  /**
   * A preparation only lives as long as the process running the clone, so a
   * row still marked `preparing` at startup is from a run that is over. It is
   * reported as failed rather than left spinning forever.
   */
  reconcilePreparations(): void {
    for (const repository of this.repositories.listWorkspaceRepositories())
      if (repository.status === "preparing")
        this.repositories.updateWorkspaceRepository({
          ...repository,
          status: "failed",
          statusError: "Preparation was interrupted before it finished",
        });
  }

  async get(workspaceReference: string): Promise<WorkspaceContent> {
    const workspace = await this.workspaces.get(workspaceReference);
    await ensureWorkspaceContentFiles(
      workspace.path,
      this.config.home,
      this.config.workspaceInstructionFilesEnabled,
    );
    const repositories = this.repositories.listWorkspaceRepositories(
      workspace.id,
    );
    const worktrees = this.repositories.listSessionWorktrees({
      workspaceId: workspace.id,
    });
    const content: WorkspaceContent = {
      workspaceId: workspace.id,
      brief: await readTextFile(join(workspace.path, "BRIEF.md")),
      journal: await readTextFile(join(workspace.path, "JOURNAL.md")),
      files: await this.listDirectory(workspace.id),
      // Status comes from the cache, never from git on this path. Reading it
      // inline cost 200–800 ms per call — dominated by the size of the working
      // trees rather than their number — and every one of those milliseconds
      // sat between the user and a list the database already had. A repository
      // whose status has not been measured yet simply has none; the refresh
      // below fills it in and says so.
      repositories: repositories.map((repository) => {
        const status = repository.referencePath
          ? this.gitStatusCache.get(statusKey(repository.referencePath))
          : undefined;
        return { ...repository, ...(status ? { gitStatus: status } : {}) };
      }),
      worktrees: worktrees.map((worktree) => {
        const status = this.gitStatusCache.get(statusKey(worktree.path));
        return { ...worktree, ...(status ? { gitStatus: status } : {}) };
      }),
    };
    // Scheduled after the answer is built, not before. Starting it first let
    // this call race a refresh it had started itself: the three file reads
    // above are all the time git needs on a small repository, so the same
    // listing sometimes carried a status and sometimes did not, decided by
    // whichever finished first on that machine. Whatever this measures belongs
    // to the next listing, which is what "listing never waits for git" has to
    // mean if it is to mean anything.
    this.scheduleGitStatusRefresh(workspace.id);
    return content;
  }

  /**
   * Every registered session worktree, with whatever status and pull request
   * has been measured, for the board. Like `get`, it never waits for git or
   * `gh`: the answer comes from the cache and a refresh is scheduled behind
   * it, so the board shows a worktree's delta without the workspace view ever
   * having been opened.
   */
  listWorktrees(): SessionWorktree[] {
    const worktrees = this.repositories.listSessionWorktrees({});
    this.scheduleGitStatusRefresh(null);
    return worktrees.map((worktree) => {
      const key = statusKey(worktree.path);
      const status = this.gitStatusCache.get(key);
      const pullRequest = this.pullRequestCache.get(key)?.value;
      return {
        ...worktree,
        ...(status ? { gitStatus: status } : {}),
        ...(pullRequest ? { pullRequest } : {}),
      };
    });
  }

  /**
   * Measures every working tree in a workspace and announces when the answers
   * change.
   *
   * Coalesced and rate limited: a burst of changes produces one pass, not one
   * per change. `force` is for the actions that just moved something and want
   * the row to catch up immediately.
   */
  private scheduleGitStatusRefresh(
    workspaceId: string | null,
    force = false,
  ): void {
    if (this.statusRefresh) {
      // Only a forced request is worth a second pass; an ordinary one is
      // already being answered by the pass in flight or the next listing.
      if (force)
        this.statusRefreshAgain =
          this.statusRefreshAgain === undefined ||
          this.statusRefreshAgain === workspaceId
            ? workspaceId
            : null;
      return;
    }
    const since = Date.now() - this.lastStatusRefreshAt;
    if (!force && since < STATUS_REFRESH_INTERVAL_MS) return;
    this.statusRefresh = this.refreshGitStatuses(workspaceId)
      .catch(() => undefined)
      .finally(() => {
        this.statusRefresh = undefined;
        this.lastStatusRefreshAt = Date.now();
        const again = this.statusRefreshAgain;
        if (again !== undefined) {
          this.statusRefreshAgain = undefined;
          this.scheduleGitStatusRefresh(again, true);
        }
      });
  }

  private async refreshGitStatuses(workspaceId: string | null): Promise<void> {
    const repositories = this.repositories.listWorkspaceRepositories(
      workspaceId ?? undefined,
    );
    const baseBranches = new Map(
      repositories.map((item) => [item.id, item.baseBranch]),
    );
    // Only a session worktree carries a branch, and only a branch can have a
    // pull request; the read-only checkouts under `repos/` never do.
    const targets: Array<{
      path: string | null;
      baseBranch: string | null;
      branchName?: string;
    }> = [
      ...repositories.map((item) => ({
        path: item.status === "ready" ? item.referencePath : null,
        baseBranch: item.baseBranch,
      })),
      ...this.repositories
        .listSessionWorktrees(workspaceId ? { workspaceId } : {})
        .map((item) => ({
          path: item.path,
          baseBranch: baseBranches.get(item.repositoryId) ?? null,
          branchName: item.branchName,
        })),
    ];
    let changed = false;
    await Promise.all(
      targets.map(async (target) => {
        if (!target.path) return;
        const status = await gitStatusAt(target.path, target.baseBranch);
        const key = statusKey(target.path);
        const previous = this.gitStatusCache.get(key);
        // A branch with no commits of its own has nothing to open a pull
        // request for, so it costs no `gh` call. One that had a link keeps
        // being checked, so a closed or merged state still arrives.
        if (
          target.branchName &&
          (status.ahead > 0 || this.pullRequestCache.get(key)?.value) &&
          (await this.refreshPullRequest(key, target.path, target.branchName))
        )
          changed = true;
        if (
          previous &&
          previous.state === status.state &&
          previous.changedFiles === status.changedFiles &&
          previous.ahead === status.ahead &&
          previous.behind === status.behind &&
          previous.filesAhead === status.filesAhead
        )
          return;
        this.gitStatusCache.set(key, status);
        changed = true;
      }),
    );
    if (changed) this.onRepositoriesChanged();
  }

  /**
   * Asks `gh` whether this branch has a pull request, at most once a minute
   * per worktree. Returns whether the answer changed.
   *
   * Every failure is silence: `gh` missing, signed out, offline, or a branch
   * that was never pushed all leave the card without a link, which is the
   * whole of what the board promises about pull requests.
   */
  private async refreshPullRequest(
    key: string,
    path: string,
    branchName: string,
  ): Promise<boolean> {
    const cached = this.pullRequestCache.get(key);
    if (cached && Date.now() - cached.checkedAt < PULL_REQUEST_REFRESH_MS)
      return false;
    const gh = findExecutable("gh", GH_EXECUTABLE_FALLBACKS);
    if (!gh || !(await pathExists(path))) {
      this.pullRequestCache.set(key, { checkedAt: Date.now() });
      return cached?.value !== undefined;
    }
    const response = await runCommand(
      gh,
      ["pr", "view", branchName, "--json", "number,url,state,isDraft"],
      { cwd: path, env: { GH_PROMPT_DISABLED: "1" } },
    ).catch(() => undefined);
    const value =
      response && response.exitCode === 0
        ? parsePullRequestView(response.stdout)
        : undefined;
    this.pullRequestCache.set(key, {
      checkedAt: Date.now(),
      ...(value ? { value } : {}),
    });
    return !samePullRequest(cached?.value, value);
  }

  async setInstructionFilesEnabled(enabled: boolean): Promise<void> {
    const workspaces = await this.workspaces.listWithHealth();
    await Promise.all(
      workspaces
        .filter((item) => item.available)
        .map((item) =>
          syncWorkspaceInstructionFiles(
            item.workspace.path,
            enabled,
            this.config.home,
          ),
        ),
    );
    await saveWorkspaceInstructionFilesEnabled(this.config, enabled);
  }

  listRepositoryLibrary(): RepositoryLibraryEntry[] {
    return this.repositories.listRepositoryLibrary();
  }

  async discoverGitHubRepositories(): Promise<{
    githubCliAvailable: boolean;
    authenticated: boolean;
    repositories: Array<{
      name: string;
      nameWithOwner: string;
      remoteUrl: string;
    }>;
    error?: string;
  }> {
    const gh = findExecutable("gh", GH_EXECUTABLE_FALLBACKS);
    if (!gh)
      return {
        githubCliAvailable: false,
        authenticated: false,
        repositories: [],
      };
    const environment = { GH_PROMPT_DISABLED: "1" };
    const response = await runCommand(
      gh,
      [
        "api",
        "--paginate",
        "--slurp",
        "-X",
        "GET",
        "user/repos",
        "-f",
        "per_page=100",
        "-f",
        "affiliation=owner,collaborator,organization_member",
        "-f",
        "sort=updated",
      ],
      { env: environment },
    );
    if (response.exitCode !== 0) {
      const detail = response.stderr.trim() || response.stdout.trim();
      const authenticationFailed =
        /auth|credential|login|token|401|bad credentials/i.test(detail);
      return {
        githubCliAvailable: true,
        authenticated: !authenticationFailed,
        repositories: [],
        error: authenticationFailed
          ? "Sign in with `gh auth login` to discover GitHub repositories."
          : `Could not load GitHub repositories: ${detail}`,
      };
    }
    try {
      return {
        githubCliAvailable: true,
        authenticated: true,
        repositories: parseGitHubRepositoryPages(response.stdout),
      };
    } catch {
      return {
        githubCliAvailable: true,
        authenticated: true,
        repositories: [],
        error: "GitHub CLI returned an unreadable repository list.",
      };
    }
  }

  async addRepositoryToLibrary(input: {
    remoteUrl: string;
    name?: string;
    githubNameWithOwner?: string;
    /** Pre-allocated so a preparing attachment can point at its real clone. */
    id?: string;
  }): Promise<RepositoryLibraryEntry> {
    const remoteUrl = input.remoteUrl.trim();
    if (!remoteUrl || remoteUrl.length > 2048)
      throw new DaedalusError(
        "VALIDATION",
        "Repository URL or local path must contain 1–2048 characters",
      );
    const existing = this.repositories.findRepositoryLibraryEntry(remoteUrl);
    if (existing) return this.refreshRepository(existing);
    const git = findExecutable("git");
    if (!git)
      throw new DaedalusError("DEPENDENCY", "git is not available on PATH");
    const id = input.id ?? crypto.randomUUID();
    const gitDirectory = join(this.config.repositoryRoot, `${id}.git`);
    const githubNameWithOwner = input.githubNameWithOwner?.trim();
    if (
      githubNameWithOwner &&
      !/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(githubNameWithOwner)
    )
      throw new DaedalusError(
        "VALIDATION",
        "GitHub repository must use the owner/repository format",
      );
    const gh = githubNameWithOwner
      ? findExecutable("gh", GH_EXECUTABLE_FALLBACKS)
      : undefined;
    if (githubNameWithOwner && !gh)
      throw new DaedalusError(
        "DEPENDENCY",
        "GitHub CLI is no longer available on PATH",
      );
    const runClone = (extra: readonly string[]) =>
      githubNameWithOwner
        ? runCommand(
            gh!,
            [
              "repo",
              "clone",
              githubNameWithOwner,
              gitDirectory,
              "--",
              "--bare",
              ...extra,
            ],
            {
              env: {
                GH_PROMPT_DISABLED: "1",
                GIT_TERMINAL_PROMPT: "0",
              },
            },
          )
        : runCommand(
            git,
            ["clone", "--bare", ...extra, remoteUrl, gitDirectory],
            { env: GIT_NETWORK_ENVIRONMENT },
          );
    // macOS filesystems are case-insensitive, and the default ref backend
    // cannot store two branches whose names differ only in case — a real
    // repository with `task/X_Deploy-...` and `task/X_deploy-...` simply
    // refuses to finish fetching. The reftable backend has no such limit, and
    // nothing here reads refs with anything but git. Older git does not know
    // the option, so a clone that rejects it is retried plainly.
    let clone = await runClone(["--ref-format=reftable"]);
    if (clone.exitCode !== 0) {
      if (await pathExists(gitDirectory)) await removeDirectory(gitDirectory);
      clone = await runClone([]);
    }
    if (clone.exitCode !== 0) {
      if (await pathExists(gitDirectory)) await removeDirectory(gitDirectory);
      throw new DaedalusError(
        "DEPENDENCY",
        `Could not clone repository: ${clone.stderr.trim() || clone.stdout.trim()}`,
      );
    }
    const now = new Date().toISOString();
    const repository: RepositoryLibraryEntry = {
      id,
      name: repositoryName(input.name ?? remoteRepositoryName(remoteUrl)),
      remoteUrl,
      gitDirectory,
      defaultBranch: "",
      lastFetchedAt: now,
      createdAt: now,
    };
    try {
      const seeded: RepositoryLibraryEntry = {
        ...repository,
        defaultBranch: await seedRemoteTrackingRefs(git, gitDirectory),
      };
      this.repositories.createRepositoryLibraryEntry(seeded);
      return seeded;
    } catch (error) {
      await removeDirectory(gitDirectory);
      throw error;
    }
  }

  private async refreshRepository(
    repository: RepositoryLibraryEntry,
    persist = true,
  ): Promise<RepositoryLibraryEntry> {
    const git = findExecutable("git");
    if (!git)
      throw new DaedalusError("DEPENDENCY", "git is not available on PATH");
    const configure = await runCommand(
      git,
      [
        "--git-dir",
        repository.gitDirectory,
        "config",
        "remote.origin.fetch",
        REMOTE_TRACKING_REFSPEC,
      ],
      { env: GIT_NETWORK_ENVIRONMENT },
    );
    if (configure.exitCode !== 0)
      throw new DaedalusError(
        "DEPENDENCY",
        `Could not configure repository remote: ${configure.stderr.trim()}`,
      );
    const fetch = await runCommand(
      git,
      ["--git-dir", repository.gitDirectory, "fetch", "--prune", "origin"],
      { env: GIT_NETWORK_ENVIRONMENT },
    );
    if (fetch.exitCode !== 0)
      throw new DaedalusError(
        "DEPENDENCY",
        `Could not fetch the latest remote repository state: ${fetch.stderr.trim() || fetch.stdout.trim()}`,
      );
    const remoteHead = await runCommand(
      git,
      [
        "--git-dir",
        repository.gitDirectory,
        "remote",
        "set-head",
        "origin",
        "--auto",
      ],
      { env: GIT_NETWORK_ENVIRONMENT },
    );
    if (remoteHead.exitCode !== 0)
      throw new DaedalusError(
        "DEPENDENCY",
        `Could not resolve the remote default branch: ${remoteHead.stderr.trim() || remoteHead.stdout.trim()}`,
      );
    const branch = await runCommand(git, [
      "--git-dir",
      repository.gitDirectory,
      "symbolic-ref",
      "--short",
      "refs/remotes/origin/HEAD",
    ]);
    if (branch.exitCode !== 0 || !branch.stdout.trim())
      throw new DaedalusError(
        "DEPENDENCY",
        "The repository remote does not advertise a default branch",
      );
    const refreshed: RepositoryLibraryEntry = {
      ...repository,
      defaultBranch: branch.stdout.trim().replace(/^origin\//, ""),
      lastFetchedAt: new Date().toISOString(),
    };
    if (persist) this.repositories.updateRepositoryLibraryEntry(refreshed);
    return refreshed;
  }

  /**
   * Measures one repository now and records the answer, so the row the caller
   * is about to show and the row the next listing shows agree.
   */
  private async measureAndCache(
    repository: WorkspaceRepository,
  ): Promise<WorkspaceRepository> {
    const measured = await this.repositoryWithGitStatus(repository);
    if (repository.referencePath && measured.gitStatus)
      this.gitStatusCache.set(
        statusKey(repository.referencePath),
        measured.gitStatus,
      );
    return measured;
  }

  private async repositoryWithGitStatus(
    repository: WorkspaceRepository,
  ): Promise<WorkspaceRepository> {
    if (repository.status !== "ready")
      return { ...repository, gitStatus: UNAVAILABLE_STATUS };
    return {
      ...repository,
      gitStatus: await gitStatusAt(
        repository.referencePath,
        repository.baseBranch,
      ),
    };
  }

  private async worktreeWithGitStatus(
    worktree: SessionWorktree,
    baseBranchByRepositoryId: ReadonlyMap<string, string | null>,
  ): Promise<SessionWorktree> {
    return {
      ...worktree,
      gitStatus: await gitStatusAt(
        worktree.path,
        baseBranchByRepositoryId.get(worktree.repositoryId) ?? null,
      ),
    };
  }

  private requireReady(repository: WorkspaceRepository): WorkspaceRepository {
    if (repository.status === "preparing")
      throw new DaedalusError(
        "CONFLICT",
        `Repository '${repository.name}' is still being prepared`,
      );
    if (repository.status === "failed")
      throw new DaedalusError(
        "CONFLICT",
        `Repository '${repository.name}' was not prepared: ${repository.statusError ?? "unknown error"}`,
      );
    return repository;
  }

  // Fetch updates the shared clone every workspace and worktree resolves
  // against, so it is what makes "behind 3" true again without touching a
  // single working tree.
  async fetchRepository(id: string): Promise<WorkspaceRepository> {
    const repository = this.repositories.findWorkspaceRepository(id);
    if (!repository)
      throw new DaedalusError(
        "NOT_FOUND",
        `Workspace repository '${id}' was not found`,
      );
    this.requireReady(repository);
    if (!repository.libraryRepositoryId)
      throw new DaedalusError(
        "CONFLICT",
        `Repository '${repository.name}' has no shared clone to fetch`,
      );
    const libraryRepository = this.repositories.findRepositoryLibraryEntry(
      repository.libraryRepositoryId,
    );
    if (!libraryRepository)
      throw new DaedalusError(
        "NOT_FOUND",
        "The shared repository clone is no longer available",
      );
    const refreshed = await this.refreshRepository(libraryRepository);
    const updated: WorkspaceRepository = {
      ...repository,
      fetchedAt: refreshed.lastFetchedAt,
    };
    this.repositories.updateWorkspaceRepository(updated);
    return this.measureAndCache(updated);
  }

  // Pushing publishes an agent's branch, so it is never implicit: nothing in
  // Daedalus pushes on its own, and the branch is always the worktree's own.
  async pushSessionWorktree(input: {
    session: string;
    repository: string;
  }): Promise<{ worktree: SessionWorktree; alreadyUpToDate: boolean }> {
    const session = this.repositories.findAgent(input.session);
    if (!session)
      throw new DaedalusError(
        "NOT_FOUND",
        `Agent session '${input.session}' was not found`,
      );
    const repository = this.repositories
      .listWorkspaceRepositories(session.workspaceId)
      .find(
        (item) =>
          item.id === input.repository || item.name === input.repository,
      );
    if (!repository)
      throw new DaedalusError(
        "NOT_FOUND",
        `Repository '${input.repository}' is not attached to this session's workspace`,
      );
    const worktree = this.repositories
      .listSessionWorktrees({ sessionId: session.id })
      .find((item) => item.repositoryId === repository.id);
    if (!worktree)
      throw new DaedalusError(
        "NOT_FOUND",
        `Session '${session.id}' has no ${repository.name} working tree`,
      );
    if (!(await pathExists(worktree.path)))
      throw new DaedalusError(
        "NOT_FOUND",
        `The ${repository.name} working tree is no longer on disk`,
      );
    const git = findExecutable("git");
    if (!git)
      throw new DaedalusError("DEPENDENCY", "git is not available on PATH");
    const result = await runCommand(
      git,
      [
        "-C",
        worktree.path,
        "push",
        "--set-upstream",
        "origin",
        `${worktree.branchName}:${worktree.branchName}`,
      ],
      { env: GIT_NETWORK_ENVIRONMENT },
    );
    const output = `${result.stderr}\n${result.stdout}`;
    if (result.exitCode !== 0)
      throw new DaedalusError(
        "CONFLICT",
        `Could not push ${worktree.branchName}: ${result.stderr.trim() || result.stdout.trim()}`,
      );
    const measured = await this.worktreeWithGitStatus(
      worktree,
      new Map([[repository.id, repository.baseBranch]]),
    );
    if (measured.gitStatus)
      this.gitStatusCache.set(statusKey(worktree.path), measured.gitStatus);
    return {
      worktree: measured,
      alreadyUpToDate: /Everything up-to-date/i.test(output),
    };
  }

  /**
   * Opens a session's worktree for review: in the first editor found on this
   * machine (VS Code, Cursor, Zed, by their command-line launchers), or in
   * Finder when there is none. The path comes from the worktree registry,
   * never from the caller, so this cannot be pointed at anything else.
   */
  async openSessionWorktree(input: {
    session: string;
    repository: string;
  }): Promise<{ path: string; openedWith: string }> {
    const session = this.repositories.findAgent(input.session);
    if (!session)
      throw new DaedalusError(
        "NOT_FOUND",
        `Agent session '${input.session}' was not found`,
      );
    const worktree = this.repositories
      .listSessionWorktrees({ sessionId: session.id })
      .find((item) => {
        if (item.repositoryId === input.repository) return true;
        const repository = this.repositories
          .listWorkspaceRepositories(session.workspaceId)
          .find((candidate) => candidate.id === item.repositoryId);
        return repository?.name === input.repository;
      });
    if (!worktree)
      throw new DaedalusError(
        "NOT_FOUND",
        `Session '${session.id}' has no '${input.repository}' working tree`,
      );
    if (!(await pathExists(worktree.path)))
      throw new DaedalusError(
        "NOT_FOUND",
        `The working tree at '${worktree.path}' no longer exists`,
      );
    for (const editor of EDITOR_LAUNCHERS) {
      const executable = findExecutable(editor.command, editor.fallbacks);
      if (!executable) continue;
      const result = await runCommand(executable, [worktree.path]);
      if (result.exitCode === 0)
        return { path: worktree.path, openedWith: editor.name };
    }
    const open = findExecutable("open", standardExecutableFallbacks("open"));
    if (!open)
      throw new DaedalusError(
        "DEPENDENCY",
        "Nothing on this machine can open a folder",
      );
    const result = await runCommand(open, [worktree.path]);
    if (result.exitCode !== 0)
      throw new DaedalusError(
        "INTERNAL",
        `Could not open ${worktree.path}: ${result.stderr.trim()}`,
      );
    return { path: worktree.path, openedWith: "Finder" };
  }

  // Removing a working tree destroys whatever is only in it, so the guard is
  // the point: a tree is removable without `force` only when it has nothing
  // uncommitted and no commit the base branch does not already have. Those two
  // facts together mean nothing can be lost.
  async removeSessionWorktree(input: {
    session: string;
    repository: string;
    force?: boolean;
  }): Promise<SessionWorktree> {
    const session = this.repositories.findAgent(input.session);
    if (!session)
      throw new DaedalusError(
        "NOT_FOUND",
        `Agent session '${input.session}' was not found`,
      );
    const repository = this.repositories
      .listWorkspaceRepositories(session.workspaceId)
      .find(
        (item) =>
          item.id === input.repository || item.name === input.repository,
      );
    if (!repository)
      throw new DaedalusError(
        "NOT_FOUND",
        `Repository '${input.repository}' is not attached to this session's workspace`,
      );
    const worktree = this.repositories
      .listSessionWorktrees({ sessionId: session.id })
      .find((item) => item.repositoryId === repository.id);
    if (!worktree)
      throw new DaedalusError(
        "NOT_FOUND",
        `Session '${session.id}' has no ${repository.name} working tree`,
      );
    if (!input.force) {
      const held = await worktreeHeldWork(repository, worktree);
      if (held.uncommittedFiles > 0)
        throw new DaedalusError(
          "CONFLICT",
          `The ${repository.name} working tree has ${held.uncommittedFiles} uncommitted ${held.uncommittedFiles === 1 ? "change" : "changes"}; commit and push them, or remove it with force`,
        );
      if (held.unreachableCommits > 0)
        throw new DaedalusError(
          "CONFLICT",
          `The ${repository.name} working tree has ${held.unreachableCommits} ${held.unreachableCommits === 1 ? "commit that exists" : "commits that exist"} nowhere else; push the branch, or remove it with force`,
        );
    }
    await this.discardWorktree(repository, worktree);
    return worktree;
  }

  // The filesystem removal, with no opinion about whether it is safe: callers
  // own that. Registration is cleared even when the directory is already gone,
  // because a row pointing at nothing is exactly what used to make a
  // repository permanently undetachable.
  private async discardWorktree(
    repository: WorkspaceRepository,
    worktree: SessionWorktree,
  ): Promise<void> {
    const git = findExecutable("git");
    if (!git)
      throw new DaedalusError("DEPENDENCY", "git is not available on PATH");
    const sourceArguments = repository.libraryRepositoryId
      ? ["--git-dir", repository.canonicalPath]
      : ["-C", repository.canonicalPath];
    const removed = await runCommand(git, [
      ...sourceArguments,
      "worktree",
      "remove",
      "--force",
      worktree.path,
    ]);
    if (removed.exitCode !== 0 && (await pathExists(worktree.path)))
      throw new DaedalusError(
        "CONFLICT",
        `Could not remove the ${repository.name} working tree: ${removed.stderr.trim() || removed.stdout.trim()}`,
      );
    await runCommand(git, [...sourceArguments, "worktree", "prune"]);
    // The branch only ever existed to carry this tree's work.
    await runCommand(git, [
      ...sourceArguments,
      "branch",
      "-D",
      worktree.branchName,
    ]);
    this.gitStatusCache.delete(statusKey(worktree.path));
    this.repositories.deleteSessionWorktree(worktree.sessionId, repository.id);
  }

  // Called when a session is archived. Only trees that provably hold nothing —
  // no uncommitted change, no commit the base branch lacks — are cleared, so
  // archiving never destroys an agent's work. Anything else is left for the
  // user to deal with deliberately.
  async releaseSessionWorktrees(sessionId: string): Promise<SessionWorktree[]> {
    const worktrees = this.repositories.listSessionWorktrees({ sessionId });
    if (worktrees.length === 0) return [];
    const released: SessionWorktree[] = [];
    for (const worktree of worktrees) {
      const repository = this.repositories.findWorkspaceRepository(
        worktree.repositoryId,
      );
      if (!repository) continue;
      const held = await worktreeHeldWork(repository, worktree);
      if (held.uncommittedFiles > 0 || held.unreachableCommits > 0) continue;
      await this.discardWorktree(repository, worktree);
      released.push(worktree);
    }
    return released;
  }

  async syncRepository(id: string): Promise<WorkspaceRepository> {
    const repository = this.repositories.findWorkspaceRepository(id);
    if (!repository)
      throw new DaedalusError(
        "NOT_FOUND",
        `Workspace repository '${id}' was not found`,
      );
    this.requireReady(repository);
    const workspace = await this.workspaces.getActive(repository.workspaceId);
    if (
      !repository.referencePath ||
      !repository.libraryRepositoryId ||
      !isPathInside(join(workspace.path, "repos"), repository.referencePath)
    )
      throw new DaedalusError(
        "CONFLICT",
        "Only managed workspace repository checkouts can be synchronized",
      );
    const currentStatus = await this.repositoryWithGitStatus(repository);
    if ((currentStatus.gitStatus?.changedFiles ?? 0) > 0)
      throw new DaedalusError(
        "CONFLICT",
        `Repository '${repository.name}' has local changes; preserve or discard them before synchronizing`,
      );
    const libraryRepository = this.repositories.findRepositoryLibraryEntry(
      repository.libraryRepositoryId,
    );
    if (!libraryRepository)
      throw new DaedalusError(
        "NOT_FOUND",
        "The shared repository clone is no longer available",
      );
    const refreshed = await this.refreshRepository(libraryRepository);
    const git = findExecutable("git");
    if (!git)
      throw new DaedalusError("DEPENDENCY", "git is not available on PATH");
    const target = await runCommand(git, [
      "--git-dir",
      refreshed.gitDirectory,
      "rev-parse",
      `refs/remotes/origin/${refreshed.defaultBranch}^{commit}`,
    ]);
    const targetCommit = target.stdout.trim();
    if (target.exitCode !== 0 || !/^[0-9a-f]{40,64}$/i.test(targetCommit))
      throw new DaedalusError(
        "DEPENDENCY",
        `Could not resolve the latest ${refreshed.defaultBranch} commit`,
      );
    const current = await runCommand(git, [
      "-C",
      repository.referencePath,
      "rev-parse",
      "HEAD",
    ]);
    const currentCommit = current.stdout.trim();
    if (current.exitCode !== 0)
      throw new DaedalusError(
        "DEPENDENCY",
        `Could not read the current ${repository.name} commit`,
      );
    if (currentCommit !== targetCommit) {
      const fastForward = await runCommand(git, [
        "--git-dir",
        refreshed.gitDirectory,
        "merge-base",
        "--is-ancestor",
        currentCommit,
        targetCommit,
      ]);
      if (fastForward.exitCode !== 0)
        throw new DaedalusError(
          "CONFLICT",
          `Repository '${repository.name}' has diverged from ${refreshed.defaultBranch}; automatic synchronization was stopped`,
        );
      const checkout = await runCommand(git, [
        "-C",
        repository.referencePath,
        "checkout",
        "--detach",
        targetCommit,
      ]);
      if (checkout.exitCode !== 0)
        throw new DaedalusError(
          "DEPENDENCY",
          `Could not update '${repository.name}': ${checkout.stderr.trim() || checkout.stdout.trim()}`,
        );
    }
    const updated: WorkspaceRepository = {
      ...repository,
      baseBranch: refreshed.defaultBranch,
      baseCommit: targetCommit,
      fetchedAt: refreshed.lastFetchedAt,
    };
    this.repositories.updateWorkspaceRepository(updated);
    return this.measureAndCache(updated);
  }

  async listDirectory(
    workspaceReference: string,
    requestedPath = "",
  ): Promise<WorkspaceFileEntry[]> {
    const workspace = await this.workspaces.get(workspaceReference);
    const { target, relativePath } = await this.resolveVisiblePath(
      workspace,
      requestedPath,
    );
    const targetStat = await lstat(target);
    if (!targetStat.isDirectory())
      throw new DaedalusError(
        "VALIDATION",
        `'${requestedPath}' is not a directory`,
      );
    const entries = await readdir(target, { withFileTypes: true });
    return entries
      .filter(
        (entry) =>
          entry.name !== ".git" && (relativePath || entry.name !== ".daedalus"),
      )
      .map((entry) => {
        const path = join(relativePath, entry.name);
        return {
          name: entry.name,
          path,
          kind: entry.isSymbolicLink()
            ? ("symlink" as const)
            : entry.isDirectory()
              ? ("directory" as const)
              : ("file" as const),
          // Carried per row so the renderer never needs a second copy of the
          // rule. A symlink is never offered either: the viewer refuses to
          // open one, and following it out of the workspace is the escape
          // every guard here exists to prevent.
          ...immutableEntryFields(
            entry.isSymbolicLink()
              ? {
                  code: "VALIDATION",
                  message: "Symbolic links cannot be changed here",
                }
              : this.immutableReason({
                  workspaceId: workspace.id,
                  relativePath: path,
                  target: join(target, entry.name),
                }),
          ),
        };
      })
      .sort((left, right) => {
        const rank = (kind: WorkspaceFileEntry["kind"]) =>
          kind === "directory" ? 0 : kind === "file" ? 1 : 2;
        return (
          rank(left.kind) - rank(right.kind) ||
          left.name.localeCompare(right.name)
        );
      });
  }

  async readFile(
    workspaceReference: string,
    requestedPath: string,
  ): Promise<WorkspaceFile> {
    const workspace = await this.workspaces.get(workspaceReference);
    const { target, relativePath } = await this.resolveVisiblePath(
      workspace,
      requestedPath,
    );
    const targetStat = await lstat(target);
    if (targetStat.isSymbolicLink())
      throw new DaedalusError(
        "VALIDATION",
        "Symbolic links cannot be opened in the workspace viewer",
      );
    if (!targetStat.isFile())
      throw new DaedalusError("VALIDATION", `'${requestedPath}' is not a file`);
    if (targetStat.size > MAX_VIEWABLE_FILE_BYTES)
      throw new DaedalusError(
        "VALIDATION",
        "Files larger than 1 MB cannot be opened in the workspace viewer",
      );
    const bytes = new Uint8Array(await Bun.file(target).arrayBuffer());
    if (bytes.subarray(0, Math.min(bytes.length, 8192)).includes(0))
      throw new DaedalusError(
        "VALIDATION",
        "Binary files cannot be opened in the workspace viewer",
      );
    return {
      name: basename(relativePath),
      path: relativePath,
      content: new TextDecoder().decode(bytes),
      format: [".md", ".mdx", ".markdown"].includes(
        extname(relativePath).toLowerCase(),
      )
        ? "markdown"
        : "text",
    };
  }

  async writeFile(input: {
    workspace: string;
    path: string;
    content: string;
    expectedContent: string;
  }): Promise<WorkspaceFile> {
    const workspace = await this.workspaces.getActive(input.workspace);
    const { target, relativePath } = await this.resolveVisiblePath(
      workspace,
      input.path,
    );
    if (relativePath.split(/[\\/]/)[0] === "repos")
      throw new DaedalusError(
        "CONFLICT",
        "Workspace repository references are read-only; edit a session worktree instead",
      );
    const targetStat = await lstat(target);
    if (!targetStat.isFile() || targetStat.isSymbolicLink())
      throw new DaedalusError(
        "VALIDATION",
        "Only regular workspace files can be edited",
      );
    if (
      new TextEncoder().encode(input.content).byteLength >
      MAX_VIEWABLE_FILE_BYTES
    )
      throw new DaedalusError(
        "VALIDATION",
        "Files larger than 1 MB cannot be saved in the workspace editor",
      );
    const current = await readTextFile(target);
    if (current !== input.expectedContent)
      throw new DaedalusError(
        "CONFLICT",
        `Workspace file '${input.path}' changed outside the editor; reopen it before saving`,
      );
    const temporaryPath = join(
      dirname(target),
      `.${basename(target)}.${crypto.randomUUID()}.tmp`,
    );
    try {
      await writeFile(temporaryPath, input.content, {
        flag: "wx",
        mode: targetStat.mode,
      });
      await rename(temporaryPath, target);
    } finally {
      await rm(temporaryPath, { force: true });
    }
    return this.readFile(workspace.id, input.path);
  }

  async createEntry(input: {
    workspace: string;
    parentPath?: string;
    name: string;
    kind: "file" | "directory";
  }): Promise<WorkspaceFileEntry> {
    const workspace = await this.workspaces.getActive(input.workspace);
    const name = assertEntryName(input.name);
    const parent = await this.resolveVisiblePath(
      workspace,
      input.parentPath ?? "",
    );
    this.assertWritable(parent.relativePath);
    if (!(await lstat(parent.target)).isDirectory())
      throw new DaedalusError("VALIDATION", "New entries require a folder");
    const path = join(parent.relativePath, name);
    if (parent.relativePath === "" && name === ".daedalus")
      throw new DaedalusError(
        "VALIDATION",
        "The .daedalus directory is reserved",
      );
    const target = join(parent.target, name);
    try {
      if (input.kind === "directory") await createDirectoryExclusive(target);
      else await writeTextFile(target, "");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "EEXIST")
        throw new DaedalusError(
          "CONFLICT",
          `Workspace path '${path}' already exists`,
        );
      throw error;
    }
    return this.describeEntry(workspace.id, target, path);
  }

  /**
   * Renames one entry in place. The name is a single path segment, exactly as
   * `createEntry` takes one; moving between folders is `moveEntry`.
   */
  async renameEntry(input: {
    workspace: string;
    path: string;
    name: string;
  }): Promise<WorkspaceFileEntry> {
    const workspace = await this.workspaces.getActive(input.workspace);
    const name = assertEntryName(input.name);
    const source = await this.resolveMutablePath(workspace, input.path);
    const destinationPath = join(dirname(source.relativePath), name);
    const destination = await this.resolveDestination(
      workspace,
      destinationPath,
    );
    await this.assertVacant(destination.target, source.target, destinationPath);
    await rename(source.target, destination.target);
    return this.describeEntry(
      workspace.id,
      destination.target,
      destinationPath,
    );
  }

  /**
   * Moves an entry into another folder, keeping its name. The destination is a
   * folder path, or `""` for the workspace root.
   */
  async moveEntry(input: {
    workspace: string;
    path: string;
    destinationPath: string;
  }): Promise<WorkspaceFileEntry> {
    const workspace = await this.workspaces.getActive(input.workspace);
    const source = await this.resolveMutablePath(workspace, input.path);
    const folder = await this.resolveVisiblePath(
      workspace,
      input.destinationPath,
    );
    this.assertWritable(folder.relativePath);
    if (!(await lstat(folder.target)).isDirectory())
      throw new DaedalusError(
        "VALIDATION",
        `'${input.destinationPath}' is not a folder`,
      );
    // `rename` answers this with EINVAL, which reaches the user as a bare
    // errno. A folder cannot contain itself, and saying so is cheap.
    if (
      folder.target === source.target ||
      isPathInside(source.target, folder.target)
    )
      throw new DaedalusError(
        "VALIDATION",
        "A folder cannot be moved inside itself",
      );
    const name = basename(source.relativePath);
    const destinationPath = join(folder.relativePath, name);
    if (destinationPath === source.relativePath)
      return this.describeEntry(
        workspace.id,
        source.target,
        source.relativePath,
      );
    const destination = await this.resolveDestination(
      workspace,
      destinationPath,
    );
    await this.assertVacant(destination.target, source.target, destinationPath);
    await rename(source.target, destination.target);
    return this.describeEntry(
      workspace.id,
      destination.target,
      destinationPath,
    );
  }

  /** Removes an entry, and everything under it when it is a folder. */
  async removeEntry(input: {
    workspace: string;
    path: string;
  }): Promise<WorkspaceFileEntry> {
    const workspace = await this.workspaces.getActive(input.workspace);
    const source = await this.resolveMutablePath(workspace, input.path);
    const entry = await this.describeEntry(
      workspace.id,
      source.target,
      source.relativePath,
    );
    await rm(source.target, { recursive: true, force: false });
    return entry;
  }

  /**
   * Why an entry cannot be renamed, moved or removed, or `undefined` when it
   * can be.
   *
   * The single source for both the refusal below and the `mutable` flag every
   * listing carries. Keeping those apart is exactly what let the menu offer a
   * delete that the service would quietly undo.
   */
  private immutableReason(input: {
    workspaceId: string;
    relativePath: string;
    target: string;
  }): { code: "VALIDATION" | "CONFLICT"; message: string } | undefined {
    const { relativePath } = input;
    if (relativePath === "")
      return {
        code: "VALIDATION",
        message: "The workspace root itself cannot be changed",
      };
    if (relativePath.split(/[\\/]/)[0] === "repos")
      return {
        code: "CONFLICT",
        message: "Reference checkouts are read-only",
      };
    if (MANAGED_WORKSPACE_DIRECTORIES.includes(relativePath))
      return {
        code: "CONFLICT",
        message: `Daedalus manages ${relativePath}/`,
      };
    if (REGENERATED_WORKSPACE_ENTRIES.includes(relativePath))
      return {
        code: "CONFLICT",
        message:
          relativePath.startsWith(".") ||
          relativePath === "AGENTS.md" ||
          relativePath === "CLAUDE.md"
            ? `Daedalus generates ${relativePath} — turn off instruction files in Settings to remove it`
            : `Daedalus regenerates ${relativePath}, so removing it would not stick`,
      };
    const worktree = this.repositories
      .listSessionWorktrees({ workspaceId: input.workspaceId })
      .find((candidate) => resolve(candidate.path) === input.target);
    if (worktree)
      return {
        code: "CONFLICT",
        message: "A session working tree — remove it from its session",
      };
    return undefined;
  }

  private async describeEntry(
    workspaceId: string,
    target: string,
    relativePath: string,
  ): Promise<WorkspaceFileEntry> {
    const entry = await lstat(target);
    return {
      name: basename(relativePath),
      path: relativePath,
      kind: entry.isSymbolicLink()
        ? "symlink"
        : entry.isDirectory()
          ? "directory"
          : "file",
      ...immutableEntryFields(
        this.immutableReason({ workspaceId, relativePath, target }),
      ),
    };
  }

  /**
   * `repos/` holds pinned read-only checkouts the repository library owns, and
   * the renderer already disables the actions that would write there. It is
   * checked again here because a service that trusts its caller is not a
   * guard — the RPC surface is reachable without the UI.
   */
  private assertWritable(relativePath: string): void {
    if (relativePath.split(/[\\/]/)[0] === "repos")
      throw new DaedalusError(
        "CONFLICT",
        "Workspace repository references are managed and read-only",
      );
  }

  /**
   * Resolves an existing path that is about to be renamed, moved or removed.
   *
   * Beyond the escape guard this refuses the entries Daedalus itself keeps
   * pointing at: the workspace root, the managed top-level folders, and any
   * registered session worktree. Every one of those has a database row naming
   * its path, and renaming it would not fail — it would quietly orphan the
   * row and leave an agent's working tree unreachable.
   */
  private async resolveMutablePath(
    workspace: Workspace,
    requestedPath: string,
  ): Promise<{ target: string; relativePath: string }> {
    const resolved = await this.resolveVisiblePath(workspace, requestedPath);
    const refusal = this.immutableReason({
      workspaceId: workspace.id,
      relativePath: resolved.relativePath,
      target: resolved.target,
    });
    if (refusal) throw new DaedalusError(refusal.code, refusal.message);
    return resolved;
  }

  /**
   * Resolves a path that is not supposed to exist yet. `resolveVisiblePath`
   * cannot do this — it requires the target to exist — so the parent is
   * resolved through it and the new segment joined on, which is how
   * `createEntry` reaches the same guarantee.
   */
  private async resolveDestination(
    workspace: Workspace,
    requestedPath: string,
  ): Promise<{ target: string; relativePath: string }> {
    const parent = await this.resolveVisiblePath(
      workspace,
      dirname(requestedPath) === "." ? "" : dirname(requestedPath),
    );
    this.assertWritable(parent.relativePath);
    const name = basename(requestedPath);
    if (parent.relativePath === "" && name === ".daedalus")
      throw new DaedalusError(
        "VALIDATION",
        "The .daedalus directory is reserved",
      );
    return {
      target: join(parent.target, name),
      relativePath: join(parent.relativePath, name),
    };
  }

  /**
   * Refuses to land on something that is already there.
   *
   * This is not politeness: `rename` overwrites an existing file silently and
   * reports success, so without this check renaming `notes.md` onto
   * `README.md` destroys `README.md` and says nothing.
   *
   * The exception is the one this filesystem makes. macOS is case-insensitive
   * but case-preserving, so `README.md` "already exists" when the file on disk
   * is `Readme.md` — and refusing there would make a case-only rename
   * impossible. `realpath` reports the stored spelling, so when both sides
   * resolve to the same real path they are the same entry reached by two
   * spellings, and the rename is a change of case rather than a collision.
   */
  private async assertVacant(
    target: string,
    source: string,
    relativePath: string,
  ): Promise<void> {
    if (!(await pathExists(target))) return;
    const [targetReal, sourceReal] = await Promise.all([
      canonicalPath(target),
      canonicalPath(source),
    ]);
    if (targetReal === sourceReal) return;
    throw new DaedalusError(
      "CONFLICT",
      `Workspace path '${relativePath}' already exists`,
    );
  }

  private async resolveVisiblePath(
    workspace: Workspace,
    requestedPath: string,
  ): Promise<{ target: string; relativePath: string }> {
    if (isAbsolute(requestedPath))
      throw new DaedalusError("VALIDATION", "Workspace paths must be relative");
    const target = resolve(workspace.path, requestedPath || ".");
    if (
      target !== resolve(workspace.path) &&
      !isPathInside(workspace.path, target)
    )
      throw new DaedalusError(
        "VALIDATION",
        "Workspace path escapes the workspace root",
      );
    const relativePath = relative(workspace.path, target);
    if (
      relativePath
        .split(/[\\/]/)
        .some((segment) => segment === ".daedalus" || segment === ".git")
    )
      throw new DaedalusError(
        "VALIDATION",
        "Internal workspace and Git metadata are not visible",
      );
    if (!(await pathExists(target)))
      throw new DaedalusError(
        "NOT_FOUND",
        `Workspace path '${requestedPath}' was not found`,
      );
    const [workspaceCanonical, targetCanonical] = await Promise.all([
      canonicalPath(workspace.path),
      canonicalPath(target),
    ]);
    if (
      targetCanonical !== workspaceCanonical &&
      !isPathInside(workspaceCanonical, targetCanonical)
    )
      throw new DaedalusError(
        "VALIDATION",
        "Workspace path resolves outside the workspace root",
      );
    return { target, relativePath };
  }

  async attachRepository(input: {
    workspace: string;
    libraryRepositoryId: string;
  }): Promise<WorkspaceRepository> {
    const workspace = await this.workspaces.getActive(input.workspace);
    const libraryRepository = this.repositories.findRepositoryLibraryEntry(
      input.libraryRepositoryId,
    );
    if (!libraryRepository)
      throw new DaedalusError(
        "NOT_FOUND",
        `Repository '${input.libraryRepositoryId}' was not found in the library`,
      );
    return this.checkoutLibraryEntry(
      workspace,
      await this.refreshRepository(libraryRepository),
    );
  }

  // Adding a repository and attaching it to the workspace used to be two
  // separate calls, and the second one re-fetched a clone the first had just
  // produced. They are one operation here so that freshness is established
  // exactly once.
  async addAndAttachRepository(input: {
    workspace: string;
    remoteUrl: string;
    name?: string;
    githubNameWithOwner?: string;
  }): Promise<WorkspaceRepository> {
    const workspace = await this.workspaces.getActive(input.workspace);
    const repository = await this.addRepositoryToLibrary({
      remoteUrl: input.remoteUrl,
      name: input.name,
      githubNameWithOwner: input.githubNameWithOwner,
    });
    return this.checkoutLibraryEntry(workspace, repository);
  }

  /**
   * Attaches without waiting for the clone.
   *
   * The attachment row is written immediately as `preparing` and returned, so
   * the workspace shows the repository arriving and the caller is free. The
   * clone and checkout then run on their own; the row becomes `ready`, or
   * `failed` carrying the reason. Nothing else has to stay open for it, which
   * is what stops a large history from timing out a request that was only
   * waiting.
   */
  async beginAddAndAttachRepository(input: {
    workspace: string;
    remoteUrl: string;
    name?: string;
    githubNameWithOwner?: string;
  }): Promise<WorkspaceRepository> {
    const workspace = await this.workspaces.getActive(input.workspace);
    const remoteUrl = input.remoteUrl.trim();
    if (!remoteUrl || remoteUrl.length > 2048)
      throw new DaedalusError(
        "VALIDATION",
        "Repository URL or local path must contain 1–2048 characters",
      );
    const existing = this.repositories.findRepositoryLibraryEntry(remoteUrl);
    const name = repositoryName(
      input.name ?? existing?.name ?? remoteRepositoryName(remoteUrl),
    );
    const referencePath = join(workspace.path, "repos", name);
    if (await pathExists(referencePath))
      throw new DaedalusError(
        "CONFLICT",
        `Workspace repository path '${referencePath}' already exists`,
      );
    // The clone's id is chosen here so the row can name where its checkout
    // will be rather than carry a placeholder that has to be corrected later.
    const libraryId = existing?.id ?? crypto.randomUUID();
    const pending: WorkspaceRepository = {
      id: crypto.randomUUID(),
      workspaceId: workspace.id,
      name,
      canonicalPath:
        existing?.gitDirectory ??
        join(this.config.repositoryRoot, `${libraryId}.git`),
      access: "write",
      libraryRepositoryId: null,
      referencePath: null,
      baseBranch: null,
      baseCommit: null,
      fetchedAt: null,
      createdAt: new Date().toISOString(),
      status: "preparing",
      statusError: null,
    };
    try {
      this.repositories.createWorkspaceRepository(pending);
    } catch (error) {
      if (String(error).includes("UNIQUE constraint failed"))
        throw new DaedalusError(
          "CONFLICT",
          "This repository path or name is already attached to the workspace",
        );
      throw error;
    }
    this.preparations.set(
      pending.id,
      this.prepareAttachment(pending, workspace, {
        remoteUrl,
        name: input.name,
        githubNameWithOwner: input.githubNameWithOwner,
        id: libraryId,
      }).finally(() => this.preparations.delete(pending.id)),
    );
    return pending;
  }

  /**
   * Settles when no working tree is being measured.
   *
   * `get` deliberately does not wait for git, so anything that needs the
   * measured answer rather than the last known one — a test, a caller about to
   * act on it — asks for it here.
   */
  /** `null` measures every workspace, which is what the board reads. */
  async settleGitStatus(workspaceId?: string | null): Promise<void> {
    if (!this.statusRefresh && workspaceId !== undefined)
      this.scheduleGitStatusRefresh(workspaceId, true);
    while (this.statusRefresh) await this.statusRefresh;
  }

  /** Settles when nothing is being prepared. Tests and the CLI wait on it. */
  async settlePreparations(): Promise<void> {
    while (this.preparations.size > 0)
      await Promise.all([...this.preparations.values()]);
  }

  private async prepareAttachment(
    pending: WorkspaceRepository,
    workspace: Workspace,
    library: {
      remoteUrl: string;
      name?: string;
      githubNameWithOwner?: string;
      id: string;
    },
  ): Promise<void> {
    try {
      const entry = await this.addRepositoryToLibrary(library);
      const attached = await this.checkoutLibraryEntry(
        workspace,
        entry,
        pending,
      );
      // Quitting mid-clone is normal, and the next start reconciles the row;
      // writing into a closed handle would only throw where nobody is left to
      // catch it.
      if (this.repositories.closed) return;
      this.repositories.updateWorkspaceRepository(attached);
    } catch (error) {
      if (this.repositories.closed) return;
      const row = this.repositories.findWorkspaceRepository(pending.id);
      // Detached while it was being prepared: nothing left to report to.
      if (!row) return;
      this.repositories.updateWorkspaceRepository({
        ...row,
        status: "failed",
        statusError: normalizeError(error).message,
      });
    } finally {
      if (!this.repositories.closed) this.onRepositoriesChanged();
    }
  }

  // `refreshed` must already carry the remote state this checkout is pinned to;
  // callers own the fetch so it is never paid twice.
  private async checkoutLibraryEntry(
    workspace: Workspace,
    refreshed: RepositoryLibraryEntry,
    pending?: WorkspaceRepository,
  ): Promise<WorkspaceRepository> {
    const git = findExecutable("git");
    if (!git)
      throw new DaedalusError("DEPENDENCY", "git is not available on PATH");
    const branchReference = `refs/remotes/origin/${refreshed.defaultBranch}`;
    const commit = await runCommand(git, [
      "--git-dir",
      refreshed.gitDirectory,
      "rev-parse",
      `${branchReference}^{commit}`,
    ]);
    const baseCommit = commit.stdout.trim();
    if (commit.exitCode !== 0 || !/^[0-9a-f]{40,64}$/i.test(baseCommit))
      throw new DaedalusError(
        "DEPENDENCY",
        `Could not resolve the latest ${refreshed.defaultBranch} commit after fetching`,
      );
    const name = repositoryName(refreshed.name);
    const referencePath = join(workspace.path, "repos", name);
    if (await pathExists(referencePath))
      throw new DaedalusError(
        "CONFLICT",
        `Workspace repository path '${referencePath}' already exists`,
      );
    await ensureDirectory(dirname(referencePath));
    const checkout = await runCommand(git, [
      "--git-dir",
      refreshed.gitDirectory,
      "worktree",
      "add",
      "--detach",
      referencePath,
      baseCommit,
    ]);
    if (checkout.exitCode !== 0)
      throw new DaedalusError(
        "CONFLICT",
        `Could not create the workspace repository checkout: ${checkout.stderr.trim() || checkout.stdout.trim()}`,
      );
    const item: WorkspaceRepository = {
      id: pending?.id ?? crypto.randomUUID(),
      workspaceId: workspace.id,
      name,
      canonicalPath: refreshed.gitDirectory,
      access: "write",
      libraryRepositoryId: refreshed.id,
      referencePath,
      baseBranch: refreshed.defaultBranch,
      baseCommit,
      fetchedAt: refreshed.lastFetchedAt,
      // A repository was attached when the user asked for it, not when its
      // clone happened to land, and the list is ordered by this.
      createdAt: pending?.createdAt ?? new Date().toISOString(),
      status: "ready",
      statusError: null,
    };
    if (pending) return item;
    try {
      this.repositories.createWorkspaceRepository(item);
    } catch (error) {
      await runCommand(git, [
        "--git-dir",
        refreshed.gitDirectory,
        "worktree",
        "remove",
        "--force",
        referencePath,
      ]);
      if (String(error).includes("UNIQUE constraint failed"))
        throw new DaedalusError(
          "CONFLICT",
          "This repository path or name is already attached to the workspace",
        );
      throw error;
    }
    return item;
  }

  async detachRepository(id: string): Promise<WorkspaceRepository> {
    const repository = this.repositories.findWorkspaceRepository(id);
    if (!repository)
      throw new DaedalusError(
        "NOT_FOUND",
        `Workspace repository '${id}' was not found`,
      );
    if (
      this.repositories
        .listSessionWorktrees({ workspaceId: repository.workspaceId })
        .some((worktree) => worktree.repositoryId === id)
    )
      throw new DaedalusError(
        "CONFLICT",
        "Repository has session worktrees and cannot be detached",
      );
    this.repositories.deleteWorkspaceRepository(id);
    await this.discardReferenceCheckout(repository);
    return repository;
  }

  private async discardReferenceCheckout(
    repository: WorkspaceRepository,
  ): Promise<void> {
    const git = findExecutable("git");
    if (!git || !repository.referencePath) return;
    await runCommand(git, [
      "--git-dir",
      repository.canonicalPath,
      "worktree",
      "remove",
      "--force",
      repository.referencePath,
    ]);
    await runCommand(git, [
      "--git-dir",
      repository.canonicalPath,
      "worktree",
      "prune",
    ]);
  }

  async appendJournal(input: {
    workspace: string;
    kind:
      | "decision"
      | "progress"
      | "blocker"
      | "question"
      | "handoff"
      | "completed";
    summary: string;
  }): Promise<void> {
    const workspace = await this.workspaces.getActive(input.workspace);
    const summary = input.summary.trim();
    if (!summary)
      throw new DaedalusError(
        "VALIDATION",
        "Journal summary must not be empty",
      );
    await ensureWorkspaceContentFiles(
      workspace.path,
      this.config.home,
      this.config.workspaceInstructionFilesEnabled,
    );
    await appendFile(
      join(workspace.path, "JOURNAL.md"),
      `\n## ${new Date().toISOString()} · ${input.kind}\n\n${summary}\n`,
      "utf8",
    );
  }

  async prepareSession(input: {
    workspace: Workspace;
    task?: Task;
    sessionId: string;
  }): Promise<{
    workingDirectory: string;
    worktrees: SessionWorktree[];
    references: WorkspaceRepository[];
  }> {
    await ensureWorkspaceContentFiles(
      input.workspace.path,
      this.config.home,
      this.config.workspaceInstructionFilesEnabled,
    );
    const references = this.repositories.listWorkspaceRepositories(
      input.workspace.id,
    );
    const group = input.task
      ? `${pathSegment(input.task.id, "task").slice(0, 12)}-${pathSegment(input.task.title, "task")}`
      : "unassigned";
    const workingDirectory = join(
      input.workspace.path,
      "worktrees",
      group,
      input.sessionId,
    );
    await ensureDirectory(workingDirectory);
    await ensureSessionInstructionFiles(
      workingDirectory,
      input.workspace.path,
      this.config.home,
      this.config.workspaceInstructionFilesEnabled,
    );
    return {
      workingDirectory,
      worktrees: [],
      references,
    };
  }

  // A session worktree starts from the newest commit on the repository's base
  // branch, not from `baseCommit`. `baseCommit` is pinned when the repository
  // is attached and only moves on an explicit sync, so branching from it puts
  // every new session behind by whatever has landed since the attachment —
  // and the gap only grows, which is what makes parallel agents collide.
  //
  // Freshness is best effort, never a precondition: a repository with no
  // reachable remote — local-only, or simply offline — still has to produce a
  // worktree, so resolution degrades to the pinned commit and finally to HEAD.
  private async latestWorktreeBase(
    git: string,
    sourceArguments: readonly string[],
    repository: WorkspaceRepository,
  ): Promise<string> {
    const pinned = repository.baseCommit ?? "HEAD";
    if (!repository.baseBranch) return pinned;
    const fetched = await runCommand(git, [
      ...sourceArguments,
      "fetch",
      "--prune",
      "origin",
    ]);
    if (fetched.exitCode !== 0) return pinned;
    const resolved = await runCommand(git, [
      ...sourceArguments,
      "rev-parse",
      "--verify",
      `refs/remotes/origin/${repository.baseBranch}`,
    ]);
    const commit = resolved.stdout.trim();
    return resolved.exitCode === 0 && /^[0-9a-f]{40,64}$/i.test(commit)
      ? commit
      : pinned;
  }

  async createSessionWorktree(input: {
    session: string;
    repository: string;
  }): Promise<SessionWorktree> {
    const session = this.repositories.findAgent(input.session);
    if (!session)
      throw new DaedalusError(
        "NOT_FOUND",
        `Agent session '${input.session}' was not found`,
      );
    if (session.kind !== "agent")
      throw new DaedalusError(
        "CONFLICT",
        "Repository worktrees can only be created for agent sessions",
      );
    const repository = this.repositories
      .listWorkspaceRepositories(session.workspaceId)
      .find(
        (item) =>
          item.id === input.repository || item.name === input.repository,
      );
    if (!repository)
      throw new DaedalusError(
        "NOT_FOUND",
        `Repository '${input.repository}' is not attached to this session's workspace`,
      );
    const existing = this.repositories
      .listSessionWorktrees({ sessionId: session.id })
      .find((item) => item.repositoryId === repository.id);
    if (existing) return existing;
    this.requireReady(repository);
    if (repository.access !== "write")
      throw new DaedalusError(
        "CONFLICT",
        `Repository '${repository.name}' is attached as reference-only`,
      );
    const workspace = await this.workspaces.getActive(session.workspaceId);
    const path = join(session.workingDirectory, repository.name);
    if (!isPathInside(workspace.path, path))
      throw new DaedalusError(
        "CONFLICT",
        "The session working directory is outside its workspace",
      );
    const branchScope = session.taskId ?? "unassigned";
    const branchName = `daedalus/${pathSegment(workspace.slug, "workspace")}/${pathSegment(branchScope, "task").slice(0, 16)}/${pathSegment(session.id, "session").slice(0, 24)}`;
    const git = findExecutable("git");
    if (!git)
      throw new DaedalusError("DEPENDENCY", "git is not available on PATH");
    await ensureDirectory(resolve(path, ".."));
    const sourceArguments = repository.libraryRepositoryId
      ? ["--git-dir", repository.canonicalPath]
      : ["-C", repository.canonicalPath];
    const result = await runCommand(git, [
      ...sourceArguments,
      "worktree",
      "add",
      "-b",
      branchName,
      path,
      await this.latestWorktreeBase(git, sourceArguments, repository),
    ]);
    if (result.exitCode !== 0)
      throw new DaedalusError(
        "CONFLICT",
        `Could not create worktree for ${repository.name}: ${result.stderr.trim() || result.stdout.trim()}`,
      );
    const worktree: SessionWorktree = {
      sessionId: session.id,
      repositoryId: repository.id,
      path,
      branchName,
      createdAt: new Date().toISOString(),
    };
    try {
      this.repositories.createSessionWorktree(worktree);
      this.scheduleGitStatusRefresh(session.workspaceId, true);
      return worktree;
    } catch (error) {
      await runCommand(git, [
        ...sourceArguments,
        "worktree",
        "remove",
        "--force",
        path,
      ]);
      throw error;
    }
  }
}
