// Writes the Homebrew cask for one release, for the tap at
// github.com/Bakar0/homebrew-tap (Casks/daedalus.rb), which installs as
// `brew install --cask bakar0/tap/daedalus`. The release
// workflow runs it after the DMGs are published; it can also be run by hand:
//
//   bun run scripts/homebrew-cask.ts --version 0.9.0 \
//     --arm64 artifacts/stable-macos-arm64-Daedalus.dmg \
//     --x64 artifacts/stable-macos-x64-Daedalus.dmg [--notarized] [--out path]
//
// Checksums are taken from the DMG files themselves, so the cask can only
// describe files that exist.

export interface CaskInput {
  version: string;
  sha256: { arm64: string; x64: string };
  /** Signed with a Developer ID and notarized, so Gatekeeper opens it as is. */
  notarized: boolean;
}

export const REPOSITORY = "Bakar0/daedalus";

export function caskSource({ version, sha256, notarized }: CaskInput): string {
  if (!/^\d+\.\d+\.\d+$/.test(version))
    throw new Error(`Not a release version: ${version}`);
  for (const [arch, digest] of Object.entries(sha256))
    if (!/^[0-9a-f]{64}$/.test(digest))
      throw new Error(`Not a SHA-256 for ${arch}: ${digest}`);

  // Without notarization Gatekeeper refuses a quarantined download outright
  // on Apple silicon ("damaged and can't be opened"). Homebrew quarantines
  // every cask it installs, so an unsigned build has to be released from
  // quarantine to open at all. A notarized build needs no such step.
  const quarantine = notarized
    ? ""
    : `
  # This build is not notarized. Homebrew quarantines what it installs, and
  # Gatekeeper refuses to open an unnotarized app from quarantine.
  postflight_steps do
    run "/usr/bin/xattr",
        args:           ["-dr", "com.apple.quarantine", "{{appdir}}/Daedalus.app"],
        writable_paths: ["{{appdir}}/Daedalus.app"]
  end
`;

  return `# Generated by scripts/homebrew-cask.ts in ${REPOSITORY}. Do not edit by hand.
cask "daedalus" do
  arch arm: "arm64", intel: "x64"

  version "${version}"
  sha256 arm:   "${sha256.arm64}",
         intel: "${sha256.x64}"

  url "https://github.com/${REPOSITORY}/releases/download/v#{version}/stable-macos-#{arch}-Daedalus.dmg"
  name "Daedalus"
  desc "Desktop app and CLI for running coding agents in tmux"
  homepage "https://github.com/${REPOSITORY}"

  livecheck do
    url :url
    strategy :github_latest
  end

  # The app updates itself from GitHub Releases, so \`brew upgrade\` leaves it
  # alone unless asked with --greedy.
  auto_updates true
  depends_on macos: :sonoma

  app "Daedalus.app"
  # Puts \`daedal\` on PATH. The launcher runs the CLI inside the app.
  binary "#{appdir}/Daedalus.app/Contents/Resources/bin/daedal"
${quarantine}
  # ~/.daedalus holds the user's workspaces and database, so it is never
  # removed here, not even by --zap.
  zap trash: [
    "~/Library/Application Support/dev.daedalus.app",
    "~/Library/Caches/dev.daedalus.app",
    "~/Library/Preferences/dev.daedalus.app.plist",
  ]
end
`;
}

async function sha256Of(path: string): Promise<string> {
  const file = Bun.file(path);
  if (!(await file.exists())) throw new Error(`No such file: ${path}`);
  return new Bun.CryptoHasher("sha256")
    .update(await file.arrayBuffer())
    .digest("hex");
}

if (import.meta.main) {
  const argument = (name: string) => {
    const index = process.argv.indexOf(`--${name}`);
    return index >= 0 ? process.argv[index + 1] : undefined;
  };
  const version = argument("version");
  const arm64 = argument("arm64");
  const x64 = argument("x64");
  if (!version || !arm64 || !x64) {
    console.error(
      "Usage: bun run scripts/homebrew-cask.ts --version <x.y.z> --arm64 <dmg> --x64 <dmg> [--notarized] [--out <path>]",
    );
    process.exit(2);
  }
  const source = caskSource({
    version,
    sha256: { arm64: await sha256Of(arm64), x64: await sha256Of(x64) },
    notarized: process.argv.includes("--notarized"),
  });
  const out = argument("out");
  if (out) await Bun.write(out, source);
  else process.stdout.write(source);
}
